### PR TITLE
Make sealing synchronous

### LINKED ISSUE #830: "Missing trie node XXX (path )" when IBFT block proposer commits block
`Geth/v1.8.18-stable-b422f4cb(quorum-v2.2.4)/linux-amd64/go1.10.1`

We are observing two rare occasions in our customer environment of an IBFT block proposer node complaining about missing the trie node corresponding to the state root of a mined block.

As shown below, node `0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2` proposed block 1358278, which was successfully accepted and committed by the validators, and inserted to the local blockchain. The chain proceeded as if everything was normal, except that when querying the receipt for one of the two txs included in the block, this node returned `null`. Other nodes return the correct receipt.

My understanding is that when the proposer executed the transactions locally before proposing the block, the trie nodes would have been inserted to both the state db and in-memory cache. So it's puzzling that the node complains about missing the state root trie node right after that.

```
DEBUG[09-23|12:00:36.070] Inserted new block                       number=1358277 hash=6484a1…c62f00 uncles=0 txs=4  gas=243226  elapsed=20.674ms
INFO [09-23|12:00:36.070] Imported new chain segment               blocks=1  txs=4  mgas=0.243 elapsed=20.743ms     mgasps=11.726 number=1358277 hash=6484a1…c62f00 cache=1.01mB
DEBUG[09-23|12:00:36.071] Reinjecting stale transactions           count=0
DEBUG[09-23|12:00:36.071] New round                                address=0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 old_round=0  old_seq=1358277 old_proposer=0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 new_round=0 new_seq=1358278 new_proposer=0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 valSet="[0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 0x32858bDf3ea471432dBE2bAEd92bDa77E6f73aDf 0x36a691b6c9Aa7E241BaB08CA369c527E0DD48C90 0x3E1E5Eb79326B2af97F65057eb8053695152a4EE 0x4c44EF3E1C562F448a0A9d55286A90Ed02ea016e 0xC0C1EA4C4a4b3A8216E08Ee5D8AB3Aa41843250D 0xF01a7AA991df53482aF41a1e0C13043C78AB403b]" size=7        IsProposer=true
INFO [09-23|12:00:36.071] Commit new mining work                   number=1358278 sealhash=7bb5fd…2f9491 uncles=0 txs=0  gas=0       fees=0 elapsed=270.771µs
INFO [09-23|12:00:39.178] VM returned with error                   err="evm: execution reverted"
INFO [09-23|12:00:39.178] Commit new mining work                   number=1358278 sealhash=34d7bd…26b436 uncles=0 txs=2  gas=0       fees=0 elapsed=107.901ms
DEBUG[09-23|12:00:46.568] Transaction pool status report           executable=3  queued=0 stales=0
INFO [09-23|12:00:46.573] VM returned with error                   err="evm: execution reverted"
INFO [09-23|12:00:46.660] Committed                                address=0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 hash=631dc6…bd896f number=1358278
DEBUG[09-23|12:00:46.662] Trie cache stats after commit            misses=0 unloads=0
INFO [09-23|12:00:46.758] Commit new mining work                   number=1358278 sealhash=d7bcb3…caf530 uncles=0 txs=3  gas=0       fees=0 elapsed=191.332ms
DEBUG[09-23|12:00:46.759] Trie cache stats after commit            misses=0 unloads=0
DEBUG[09-23|12:00:46.759] Dereferenced trie from memory database   nodes=0   size=0.00B    time=2.034µs     gcnodes=5312 gcsize=2.34mB   gctime=92.523811ms livenodes=4225 livesize=748.20kB
INFO [09-23|12:00:46.759] Successfully sealed new block            number=1358278 sealhash=34d7bd…26b436 hash=631dc6…bd896f elapsed=7.580s
INFO [09-23|12:00:46.759] 🔗 block reached canonical chain          number=1358271 hash=428863…c55337
INFO [09-23|12:00:46.759] 🔨 mined potential block                  number=1358278 hash=631dc6…bd896f
ERROR[09-23|12:00:46.759] Failed to create mining context          err="missing trie node f38ca7b8d75f9066821c07d51fdb607d253f87408fe339052c087d8b0db91e59 (path )"
FERROR[09-23|12:00:46.760] Failed to reset txpool state             err="missing trie node f38ca7b8d75f9066821c07d51fdb607d253f87408fe339052c087d8b0db91e59 (path )"
WARN [09-23|12:00:46.760] unexpected request                       address=0x25BddAe7B76B5d6b9cbfB6aAF8514Cd03Af263f2 state="Accept request" seq=1358279 err="old message"                                                                                number=1358278 hash=b26a4f…9b4089
DEBUG[09-23|12:00:47.085] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [09-23|12:00:47.208] sending private tx                       data=f47cc443000000000000000000000000000000000000000000000000000000000000001ba66079 .................... privatefrom= privatefor="[...............]"
INFO [09-23|12:00:47.278] sent private tx                          data=4e43b7380a3602da2f90e5e0f46969dc7f7cac68147a959a4202cbc944a5c9680a6298156f72444947b1b58225bed88409c6094340e608ffef88491a4a4c794e privatefrom= privatefor="[...................]"
INFO [09-23|12:00:47.278] Private transaction signing with QuorumPrivateTxSigner 
INFO [09-23|12:00:47.282] Setting new local account                address=0x5bED1a035B8dCA7Ba7f7eF20552d8bea12e869a5
INFO [09-23|12:00:47.285] Submitted transaction                    fullhash=0x68998b94db6ba4f805223ef84ae173e23c3207f097906e3300d6c8ce3547c68c recipient=0x08C8C5afd5A7CfEdF2019D1A0B4e179364a02BBe
INFO [09-23|12:00:49.661] sending private tx                       data=94bee323000000000000000000000000000000000000000000000000000000000000001ca793dea1d8f10bd129cf1aa0793ead9fc8e358d52ab1e058a396126fe3ec19164eb79fb3707a279c9fbd943c7f7eaf8b880a918975f3ef3b7a36cf815bfcde7c..... privatefrom= privatefor="[...................]"
INFO [09-23|12:00:49.691] sent private tx                          data=ca12f5240008dd046f9f3051cc7c55e0245497061d78184f9caa430dbede245925fa475d30b4f738fedabbfbbd2875be24c9ef3cc6736007582c8722f0f781fe...  privatefrom= privatefor="[....................]"
INFO [09-23|12:00:49.691] Private transaction signing with QuorumPrivateTxSigner 
INFO [09-23|12:00:49.698] Setting new local account                address=0x56c5A4F893C5A70A796fb999EB2e409b1EaC0c99
INFO [09-23|12:00:49.698] Submitted transaction                    fullhash=0x3efff3dc69169be768ebe86b7153606567aa4776388ae2db6838ff223f6ffd58 recipient=0x1b115BD375fb37809a6D19a97abd03490f4DF117
ERROR[09-23|12:00:49.759] Failed to create mining context          err="missing trie node f38ca7b8d75f9066821c07d51fdb607d253f87408fe339052c087d8b0db91e59 (path )"
DEBUG[09-23|12:00:53.149] Transaction pool status report           executable=5  queued=0 stales=0
ERROR[09-23|12:00:55.759] Failed to create mining context          err="missing trie node f38ca7b8d75f9066821c07d51fdb607d253f87408fe339052c087d8b0db91e59 (path )"
```

### PR DESCRIPTION
**Pull request by prd-fox**
There exists some race condition when minting blocks with IBFT/Clique.

This is where a block is created, but then discarded to try again. The state is reverted and txpool reset, but fails. This also happens as we are performing operations on a constantly changing global state, instead of copies of state.

A few issues that can happen:

- Mining stops due to the miner and txpool encountering an error. Waits for a new block to enter the network and tries again, meaning this issue only occurs on a single node network (a questionable premise).
- a panic where the state db cannot be reverted to a prior snapshot, because the state has already been recreated for the next block
- concurrent map iteration/write issues

Fixes https://github.com/jpmorganchase/quorum/issues/830

### CODE REVIEW

File: miner/worker.go [hunk 1]
```diff
@@ -585,48 +582,37 @@ func (w *worker) resultLoop() {
...
-			}
-
-			for _, log := range append(work.state.Logs(), work.privateState.Logs()...) {
-				log.BlockHash = hash
+				logs = append(logs, receipt.Logs...)
 			}
 
 			// write private transacions
-			privateStateRoot, _ := work.privateState.Commit(w.config.IsEIP158(block.Number()))
+			privateStateRoot, _ := task.privateState.Commit(w.config.IsEIP158(block.Number()))
```
Comment (amalrajmani) [inline miner/worker.go]: handle error returned by privateState.Commit, we can raise panic the way raft does. `panic(fmt.Sprint("error committing private state: ", err))`

File: miner/worker.go [hunk 2]
```diff
@@ -585,48 +582,37 @@ func (w *worker) resultLoop() {
...
 			core.WritePrivateStateRoot(w.eth.ChainDb(), block.Root(), privateStateRoot)
```
Comment (amalrajmani) [inline miner/worker.go]: handle error returned by `core.WritePrivateStateRoot(...)`

File: miner/worker.go [hunk 3]
```diff
@@ -585,48 +582,37 @@ func (w *worker) resultLoop() {
...
-			allReceipts := mergeReceipts(work.receipts, work.privateReceipts)
+			allReceipts := mergeReceipts(task.receipts, task.privateReceipts)
 
 			// Commit block and state to database.
-			w.mu.Lock()
-			stat, err := w.chain.WriteBlockWithState(block, allReceipts, work.state, nil)
-			w.mu.Unlock()
+			stat, err := w.chain.WriteBlockWithState(block, allReceipts, task.state, nil)
 			if err != nil {
-				log.Error("Failed writWriteBlockAndStating block to chain", "err", err)
```
Comment (amalrajmani) [inline miner/worker.go:612]: we should log error if  `w.chain.WriteBlockWithState(...)` fails. upstream does the same `log.Error("Failed writing block to chain", "err", err)`

**Review by trung — APPROVED** [review]
LGTM

Related to jpmorganchase/quorum#830
And also would help reverting PR jpmorganchase/quorum#684, hence permanently fix jpmorganchase/quorum#676 and jpmorganchase/quorum#653

**Review by jbhurat — APPROVED** [review]
LGTM

Verified by running the tests that failed in https://github.com/jpmorganchase/quorum/issues/653

**Review by jpmsam — APPROVED** [review]
