### PR TITLE
Fix raft applied index out of range

### LINKED ISSUE #845: 'raft applied is out of range' causing panic
I believe this is a recurence of #281

#### System information

Geth version: `geth version`
Geth
Version: 1.8.18-stable
Git Commit: c894c2d70eacf30740d03b53ed2fb39e42641295
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.12
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`
Quorum Version: 2.2.5

#### Expected behaviour

After restart the node catches up with the chain

#### Actual behaviour

Node 1 partialy catches up, restarts and panics. there after it panics every restart
Node 2 partialy catches up, restarts and panics. there after it panics every restart
Node 1 & Node 2 reach the same block, but are about 200 blocks behind the minter at that time

#### Steps to reproduce the behaviour

* 5 node network
* Continually create tx's on the nodes (load testing at moderate rate)
* Take two nodes down for a few hours .

#### Backtrace

````
TRACE[10-13|08:57:13.777|eth/sync.go:89]                         Sending batch of transactions            id=c61a11c33dfeeba2 conn=staticdial count=10 bytes=25.43kB
INFO [10-13|08:57:14.177|raft/handler.go:468]                    startRaft                                raft ID=4
INFO [10-13|08:57:14.254|raft/handler.go:471]                    remounting an existing raft log; connecting to peers.
raft2019/10/13 08:57:14 applied(11688) is out of range [prevApplied(13718), committed(13718)]
panic: applied(11688) is out of range [prevApplied(13718), committed(13718)]

goroutine 1 [running]:
log.(*Logger).Panicf(0xc00013d9f0, 0x113ea16, 0x3c, 0xc003307260, 0x3, 0x3)
        /usr/local/go/src/log/log.go:219 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x1f297f0, 0x113ea16, 0x3c, 0xc003307260, 0x3, 0x3)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raftLog).appliedTo(0xc0003fe310, 0x2da8)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/log.go:202 +0x15b
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.newRaft(0xc003a73728, 0xc0001182a0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:306 +0xa97
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.RestartNode(0xc003a73728, 0x35, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:224 +0x40
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft(0xc018d1a840)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:472 +0x7f4
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).Start(0xc018d1a840, 0xc000427180)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:142 +0xd7
github.com/ethereum/go-ethereum/raft.(*RaftService).Start(0xc018f68f00, 0xc000427180, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/backend.go:91 +0x39
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc000426f00, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:206 +0xa92
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc000426f00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc00016c160, 0xc000426f00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:292 +0xb5
main.geth(0xc00016c160, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:275 +0xe1
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xf55700, 0x11af838, 0xc00016c160, 0xc00016c160, 0xc0004f9f58)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001221a0, 0xc0000e4000, 0x23, 0x24, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x59d
main.main()
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:261 +0x55
````

#### Logs etc

We have a lot of log data from all nodes for this incident. If there is interest, I can work it into a useful shape.

### PR DESCRIPTION
**Pull request by zzy96**
Fix https://github.com/jpmorganchase/quorum/issues/845

In raft mode, `hard state` & `entries` are written into WAL before raft entries are processed, but `applied index` is written into the node's local level db only after completion of processing each raft entry. If a node is stopped/ restarted during a large list of entries under processing (particularly when calling `applyRaftSnapshot` which takes time to sync blocks from peers). `hard state` & `entries` are moving forward but `applied index` is not updated.

This fix can successfully recover the node from `applied out of range` panic state by resetting `last applied index` to `last persisted applied index` from WAL on raft restart.

### CODE REVIEW

**Review by jbhurat — DISMISSED** [review]
LGTM

**Review by trung — DISMISSED** [review]
LGTM

File: raft/handler.go [hunk 1]
```diff
@@ -426,6 +424,19 @@ func (pm *ProtocolManager) startRaft() {
 				// the single call to `pm.applyNewChainHead` for more context.
 				lastAppliedIndex = lastPersistedCommittedIndex
 			}
+
+			// fix raft applied index out of range
+			firstIndex, err := pm.raftStorage.FirstIndex()
+			if err != nil {
+				panic(fmt.Sprintf("failed to read last persisted applied index from raft while restarting: %v", err))
+			}
+			lastPersistedAppliedIndex := firstIndex - 1
```
Comment (jpmsam) [inline raft/handler.go:453]: Why `- 1` ? It seems that if we persisted the correct value earlier, then we'll overwrite it regardless.

Comment (zzy96) [reply raft/handler.go:453]: Hi @jpmsam 

This is as per the etcd raft implementation. When raft library is checking if it is out of range, the lower boundary (included) is defined as `log.applied` which is set here https://github.com/jpmorganchase/quorum/blob/b7edc0b6c9316f4633270467902833e35ca9144b/vendor/github.com/coreos/etcd/raft/log.go#L65 Therefore, `lastPersistedAppliedIndex` is set to `firstIndex - 1` if it is out of sync. It will not overwrite `firstIndex - 1` because it already becomes "last applied". Only the new entries from `firstIndex` and onwards will be applied.

**Review by jpmsam — APPROVED** [review]
