### PR TITLE
override the 5 secs default time out for eth_call

### LINKED ISSUE #1083: Execution aborted (timeout = 5s)
Hi there,

Recently I have upgraded geth and tessera to the latest version. After the upgrade, we are facing one of the most blockers is 

> getting execution aborted (timeout = 5s)

In the previous version, we are not getting these issues. Even we have less than one lakh blocks ( around 95k blocks are there). Is there any solution to fix these issues? 

Can anyone clarify this ASAP....? Thanks in advance.

#### System information

Geth version: `geth 1.9.7-stable`
OS & Version: Linux

#### Expected behaviour
We should get the data from the blockchain.

#### Actual behaviour

> err="execution aborted (timeout = 5s)"

#### Steps to reproduce the behaviour
It's happening randomly. Ex: When we are syncing the private smart contract data from the blockchain network.

#### Backtrace

````
WARN [10-03|10:01:54.054] Served eth_call                          reqid=76  t=5.161607327s err="execution aborted (timeout = 5s)"
WARN [10-03|10:01:54.134] Served eth_call                          reqid=78  t=5.058150698s err="execution aborted (timeout = 5s)"
WARN [10-03|10:01:54.261] Served eth_call                          reqid=77  t=5.311992711s err="execution aborted (timeout = 5s)"
WARN [10-03|10:01:54.461] Served eth_call                          reqid=81  t=5.198990542s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.235] Served eth_call                          reqid=128 t=5.042588426s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.348] Served eth_call                          reqid=129 t=5.155202891s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.368] Served eth_call                          reqid=132 t=5.140124889s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.408] Served eth_call                          reqid=127 t=5.219717193s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.602] Served eth_call                          reqid=133 t=5.359242588s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.781] Served eth_call                          reqid=143 t=5.268965372s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.808] Served eth_call                          reqid=131 t=5.613000588s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.815] Served eth_call                          reqid=130 t=5.620166645s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.828] Served eth_call                          reqid=139 t=5.393770983s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.955] Served eth_call                          reqid=134 t=5.683248589s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.968] Served eth_call                          reqid=142 t=5.480163235s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:45.988] Served eth_call                          reqid=138 t=5.611346017s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:46.115] Served eth_call                          reqid=135 t=5.820318627s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:46.121] Served eth_call                          reqid=140 t=5.68203593s  err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:46.128] Served eth_call                          reqid=136 t=5.810234761s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:46.188] Served eth_call                          reqid=141 t=5.727460755s err="execution aborted (timeout = 5s)"
WARN [10-03|10:02:46.195] Served eth_call                          reqid=137 t=5.821505624s err="execution aborted (timeout = 5s)"
WARN [10-03|10:07:22.518] Served eth_call                          reqid=1574 t=5.324584254s err="execution aborted (timeout = 5s)"
WARN [10-03|10:07:24.098] Served eth_call                          reqid=1580 t=5.061619423s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.386] Served eth_call                          reqid=133  t=5.12355727s  err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.446] Served eth_call                          reqid=135  t=5.139419821s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.466] Served eth_call                          reqid=142  t=5.000434662s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.726] Served eth_call                          reqid=146  t=5.170135841s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.792] Served eth_call                          reqid=145  t=5.252541727s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.799] Served eth_call                          reqid=140  t=5.377890122s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.806] Served eth_call                          reqid=132  t=5.566173481s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.812] Served eth_call                          reqid=147  t=5.235061661s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.819] Served eth_call                          reqid=141  t=5.375251038s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.826] Served eth_call                          reqid=134  t=5.542840071s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.832] Served eth_call                          reqid=143  t=5.343198793s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.852] Served eth_call                          reqid=138  t=5.476621153s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.912] Served eth_call                          reqid=137  t=5.559165756s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:50.986] Served eth_call                          reqid=139  t=5.586428045s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:51.059] Served eth_call                          reqid=144  t=5.548721573s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:51.119] Served eth_call                          reqid=136  t=5.791148623s err="execution aborted (timeout = 5s)"
WARN [10-03|10:08:51.146] Served eth_call                          reqid=148  t=5.545945095s err="execution aborted (timeout = 5s)"

````

### PR DESCRIPTION
**Pull request by vsmk98**
For `eth_call`, the default time out is set to 5 secs. If the call takes longer than 5 secs, the `evm` aborts and the call fails with error `execution aborted (timeout = 5s)`. 

There may be valid scenarios (e.g. for reporting) where the `eth_call` may take beyond the default 5s. Considering these scenarios a new flag `--vm.calltimeout` has been added to `geth` start up flags to pass the desired timeout duration for `eth_call`. The default value for this will be 5 seconds. If passed as 0 there will be no timeout.

fixes #1083

### CODE REVIEW

**Review by amalrajmani — DISMISSED** [review]
LGTM

**Review by SatpalSandhu61 — DISMISSED** [review]

**Comment by SatpalSandhu61** [comment]
LGTM

File: cmd/geth/main.go [hunk 1]
```diff
@@ -168,6 +168,7 @@ var (
 		utils.PluginLocalVerifyFlag,
 		utils.PluginPublicKeyFlag,
 		utils.AllowedFutureBlockTimeFlag,
+		utils.TimeOutForCall,
```
Comment (jbhurat) [inline cmd/geth/main.go]: Small Niptick: is it possible to name the flag `CallTimeout` instead of `TimeOutForCall`. Other than than LGTM

**Comment by trung** [comment]
Can you double check the referencing to `DoCall()` in the code to make sure the configured timeout value is used throughout? E.g.: https://github.com/ConsenSys/quorum/blob/7196f19309dd4b7c6ce17d445ee04f27ac430427/graphql/graphql.go#L897-L901

File: eth/api_backend.go [hunk 2]
```diff
@@ -49,6 +49,9 @@ type EthAPIBackend struct {
 	//
 	// hex node id from node public key
 	hexNodeId string
+
+	// if set diables the time out for eth_call
+	timeOutForCall int
```
Comment (trung) [inline eth/api_backend.go]: i would use the type: `time.Duration` here and transform arg value in the `setQuorumConfig()`

File: cmd/geth/main.go (hunk 1 above)
Comment (trung) [reply cmd/geth/main.go]: \+ postfix with `Flag`.

Another alternative is to use the same convention as `EVMIntepreterFlag`: 
```go
        EVMCallTimeoutFlag = cli.StringFlag{
		Name:  "vm.calltimeout",
		Usage: "Timeout duration in seconds for message call execution without creating a transaction. Value 0 means no timeout.",
		Value: 5,
	}
```

File: eth/api_backend.go (hunk 2 above)
Comment (vsmk98) [reply eth/api_backend.go]: Yes agree. Will save multiple transformations. Changed.

File: cmd/geth/main.go (hunk 1 above)
Comment (vsmk98) [reply cmd/geth/main.go]: I have moved the flag under the vm flags section from quorum

File: eth/api_backend.go [hunk 3]
```diff
@@ -49,6 +50,9 @@ type EthAPIBackend struct {
 	//
 	// hex node id from node public key
 	hexNodeId string
+
+	// if set diables the time out for eth_call
```
Comment (SatpalSandhu61) [inline eth/api_backend.go]: Just a minor one - the comment is no longer correct, as it sets the timeout rather than disabling it.

File: eth/config.go [hunk 4]
```diff
@@ -165,4 +165,7 @@ type Config struct {
 
 	// Istanbul block override (TODO: remove after the fork)
 	OverrideIstanbul *big.Int
+
+	// no time out fo eth_call
```
Comment (SatpalSandhu61) [inline eth/config.go]: Same with this comment.

Comment (vsmk98) [reply eth/config.go]: updated

File: eth/api_backend.go (hunk 3 above)
Comment (vsmk98) [reply eth/api_backend.go]: updated

**Review by SatpalSandhu61 — DISMISSED** [review]

**Review by amalrajmani — DISMISSED** [review]
LGTM

**Review by trung — DISMISSED** [review]
LGTM

**Review by jbhurat — DISMISSED** [review]
LGTM

**Review by jpmsam — APPROVED** [review]
